### PR TITLE
fix validation+mocking

### PR DESCRIPTION
**Pull request by povilasv**
This PR fixes validaiton + mocking using https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_proc_filter

This requires newest Envoy version v1.23

https://www.envoyproxy.io/docs/envoy/v1.23.0/version_history/v1.23/v1.23.0

image

Currently still WIP, not ready for review.

Importantly ext_proc is wip in Envoy:
```
.ext_proc.v3.ProcessingMode' is contained in proto file 'envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto' marked as work-in-progress. API features marked as work-in-progress are not considered stable, are not covered by the threat model, are not supported 
by the security team, and are subject to breaking changes. Do not use this feature without understanding each of the previous points.   
```

## Changes

-

## Fixes

- https://github.com/kubeshop/kusk-gateway/issues/311

## Checklist

- [ ] tested locally
- [x] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by jasmingacic — APPROVED** [review]
Looking good

**Comment by kylehodgetts** [comment]
@povilasv Could you include some test resources and instructions so I can quickly take it for a spin?

**Comment by jasmingacic** [comment]
> @povilasv Could you include some test resources and instructions so I can quickly take it for a spin?

We need smoke tests to validate this.

**Review by kylehodgetts — APPROVED** [review]
All good 👍

**Comment by jasmingacic** [comment]
Just don't merge it today leave it for v1.2.0 next monday

**Comment by jasmingacic** [comment]
Currently Envoy 1.23.0 image doesn't work with ARM as indicated here https://github.com/envoyproxy/envoy/issues/22701
As Envoy 1.23.0 is required for this feature to work we are putting it on hold until upstream issue is fixed.

**Comment by mbana** [comment]
> Currently Envoy 1.23.0 image doesn't work with ARM as indicated here [envoyproxy/envoy#22701](https://github.com/envoyproxy/envoy/issues/22701) As Envoy 1.23.0 is required for this feature to work we are putting it on hold until upstream issue is fixed.

https://github.com/kubeshop/kusk-gateway/pull/649 has been merged. @povilasv, you want to give this another try?

**Pull request merged**
